// QUIC packet creation, parsing, and manipulation.

const std = @import("std");
const expectEqual = std.testing.expectEqual;
const expectEqualSlices = std.testing.expectEqualSlices;

const crypto = @import("crypto.zig");
const frame = @import("frame.zig");
const tls = @import("tls.zig");
const varint = @import("varint.zig");

const QuicVersionNegotiation: u32 = 0x00000000;
const QuicVersion1: u32 = 0x00000001;

const DefaultDestConnIdLen: u8 = 8;
const DefaultSourceConnIdLen: u8 = 0;

const AuthTagSz: usize = 16;

const QuicSmallestMaxDgram: usize = 1200;

const QuicPacketError = error{
    FixedBitError, // Indicates unexpected QUICv1 long header fixed bit.
    PacketTypeError, // Indicates unknown packet type value.
};

pub const ConnectionId = struct {
    const Self = @This();

    seqno: u32 = undefined,
    bytes: []const u8 = undefined,

    pub fn init(id: []const u8, seqno: u32) ConnectionId {
        return ConnectionId{
            .seqno = seqno,
            .bytes = id,
        };
    }
};

const QuicPktType = enum(u8) {
    Initial = 0x00,
    ZeroRtt = 0x01,
    Handshake = 0x02,
    Retry = 0x03,
};

pub const QuicPacket = struct {
    const Self = @This();

    // Generic contents of a QUIC packet, based on RFC 8999.
    use_long_form: bool = undefined,
    version_specific_bits: u8 = undefined,
    version: u32 = undefined,
    dconn_id_len: u8 = undefined,
    dconn_id: ConnectionId = undefined,
    sconn_id_len: u8 = undefined,
    sconn_id: ConnectionId = undefined,

    quic_pkt_type: QuicPktType = undefined,

    // Packet number.
    pktnum: u32 = undefined,

    frames: std.ArrayList(frame.QuicFrame) = .empty,

    // TODO: only meaningful for Initial?
    token: ?[]u8 = null,
    // For some packet types, length of packet number + payload.
    len: ?usize = undefined,
    // Tag generated by AEAD.
    authtag: ?[]u8 = null,

    // Allocator for temporary buffers needed for crypto, etc.
    alloc: std.mem.Allocator = undefined,

    pub fn init(alloc: std.mem.Allocator) QuicPacket {
        return QuicPacket{
            .alloc = alloc,
        };
    }

    pub fn deinit(self: *Self) void {
        self.frames.deinit(self.alloc);
    }

    pub fn add_crypto_frame(self: *Self, crypto_body: []const u8) !void {
        const c = frame.CryptoFrame.init(crypto_body, 0);
        const f = frame.QuicFrame{
            .frame_type = frame.FrameType.CRYPTO,
            .body = frame.QuicFrameBody{ .CRYPTO = c },
        };
        try self.frames.append(self.alloc, f);
    }

    pub fn add_padding(self: *Self, padding_len: usize) !void {
        const p = frame.PaddingFrame.init(padding_len);
        const f = frame.QuicFrame{
            .frame_type = frame.FrameType.PADDING,
            .body = frame.QuicFrameBody{ .PADDING = p },
        };
        try self.frames.append(self.alloc, f);
    }

    // Make the packet a QUIC version 1 Initial packet.
    pub fn make_initial(self: *Self, rand: [32]u8) !void {
        self.use_long_form = true;
        // In version 1, the version specific bits are:
        // - 1 bit for the fixed bit (1)
        // - 2 bit for the long packet type (0 for Initial)
        // - 2 reserved bits
        // - 2 bits for packet number length
        self.version_specific_bits = 0x40; // make packet number 1 byte (TODO)
        self.version = QuicVersion1;
        self.dconn_id_len = DefaultDestConnIdLen;
        // TODO: nonsense test ID
        const dcid_bytes = [_]u32{ 0x12345678, 0x9ABCDEF0 };
        self.dconn_id = ConnectionId.init(std.mem.sliceAsBytes(dcid_bytes[0..]), 1);
        self.sconn_id_len = DefaultSourceConnIdLen;
        self.sconn_id = ConnectionId.init(&[_]u8{}, 1); // No source connection ID.

        self.quic_pkt_type = QuicPktType.Initial;
        self.pktnum = 1;

        // Make a TLS ClientHello.
        var buf = std.Io.Writer.Allocating.init(self.alloc);
        defer buf.deinit();
        var client_hello = tls.ClientHello.init(rand);
        try client_hello.serialize(&buf.writer);
        try self.add_crypto_frame(buf.written());

        var padding_needed = QuicSmallestMaxDgram;
        padding_needed -= try self.get_header_length();
        padding_needed -= try self.get_payload_length();
        try self.add_padding(padding_needed);
    }

    // Compute the packet header length.
    fn get_header_length(self: Self) !usize {
        var hlen: usize = 1; // First byte.
        if (self.use_long_form) {
            hlen += 6; // version + src & dst conn IDs.
            hlen += self.sconn_id.bytes.len;
            hlen += self.dconn_id.bytes.len;

            var token_len: usize = 0;
            if (self.token != null) token_len = self.token.?.len;
            const token_len_of_len = try varint.lenOfVarInt(token_len);
            hlen += token_len_of_len + token_len;
            const payload_len = try self.get_payload_length();
            const pktnum_len = self.get_pktnum_len();
            hlen += try varint.lenOfVarInt(payload_len + pktnum_len);
            hlen += self.get_pktnum_len();
        } else {
            // TODO short for header length.
        }

        return hlen;
    }

    // Compute the packet length value that will go into the header.
    fn get_payload_length(self: Self) !usize {
        var sz: usize = 0;
        for (self.frames.items) |f| {
            sz += try frame.get_length(&f);
        }
        if (self.authtag != null) sz += self.authtag.?.len;
        return sz;
    }

    fn find_pn_offset(self: Self) !usize {
        var pn_offset: usize = undefined;

        if (self.use_long_form) {
            const payload_len = try self.get_payload_length();
            const len_of_len = try varint.lenOfVarInt(payload_len);
            pn_offset = 7 + self.dconn_id.bytes.len + self.sconn_id_len + len_of_len;
            if (self.quic_pkt_type == QuicPktType.Initial) {
                var token_len: usize = 0;
                if (self.token != null) token_len = self.token.?.len;
                const token_len_of_len = try varint.lenOfVarInt(token_len);
                pn_offset += token_len_of_len + token_len;
            }
        } else {
            // TODO: abstract to connection ID not destination.
            pn_offset = 1 + self.dconn_id.bytes.len;
        }

        return pn_offset;
    }

    fn find_sample_offset(self: Self) !usize {
        const pn_offset = try self.find_pn_offset();
        return pn_offset + 4;
    }

    // Assumes this is a long header packet that carries a packet number.
    fn get_pktnum_len(self: Self) usize {
        return (1 + (self.version_specific_bits & 0x03));
    }

    // Serialize the packet heder (unprotected) through a writer.
    pub fn serialize_header(self: Self, w: *std.Io.Writer) !void {
        var first_byte: u8 = self.version_specific_bits & 0x7F;
        if (self.use_long_form) first_byte |= 0x80;

        try w.writeByte(first_byte);
        try w.writeByte(@as(u8, @intCast(self.version >> 24)));
        try w.writeByte(@as(u8, @intCast(self.version >> 16)));
        try w.writeByte(@as(u8, @intCast(self.version >> 8)));
        try w.writeByte(@as(u8, @intCast(self.version & 0xFF)));
        try w.writeByte(self.dconn_id_len);
        try w.writeAll(self.dconn_id.bytes);
        try w.writeByte(self.sconn_id_len);
        if (self.sconn_id_len != 0)
            try w.writeAll(self.sconn_id.bytes);

        // Determine the length field to encode.
        var len: usize = try self.get_payload_length();
        const pktnum_len = self.get_pktnum_len();
        len += pktnum_len;

        if (self.quic_pkt_type == QuicPktType.Initial) {
            var token_len: u64 = 0;
            if (self.token != null) token_len = self.token.?.len;

            try varint.writeVarInt(@as(u64, @intCast(token_len)), w);
            if (self.token != null) try w.writeAll(self.token.?);

            len += AuthTagSz;
            try varint.writeVarInt(@as(u64, @intCast(len)), w);

            if (pktnum_len > 3) try w.writeByte(@as(u8, @intCast(self.pktnum >> 24)));
            if (pktnum_len > 2) try w.writeByte(@as(u8, @intCast(self.pktnum >> 16)));
            if (pktnum_len > 1) try w.writeByte(@as(u8, @intCast(self.pktnum >> 8)));
            if (pktnum_len > 0) try w.writeByte(@as(u8, @intCast(self.pktnum)));
        }
    }

    // Seriaize the packet payload (unprotected) through a writer.
    pub fn serialize_payload(self: Self, w: *std.Io.Writer) !void {
        for (self.frames.items) |f| {
            try frame.write_frame(&f, w);
        }
    }

    // Serialize the packet into a given writer.
    // TODO: only support long headers ATM
    pub fn serialize(self: Self, w: *std.Io.Writer) !void {
        var header = std.Io.Writer.Allocating.init(self.alloc);
        defer header.deinit();
        var pt_payload = std.Io.Writer.Allocating.init(self.alloc);
        defer pt_payload.deinit();

        // Create unprotected header and payload.
        try self.serialize_header(&header.writer);
        try self.serialize_payload(&pt_payload.writer);

        // Apply payload protection.
        // TODO: Replace temp_crypto w/ crypto for Initial, etc.
        var temp_crypto = crypto.QuicCrypto.init(self.dconn_id.bytes);
        var ct_payload: []u8 = try self.alloc.alloc(u8, pt_payload.written().len);
        var tag: [AuthTagSz]u8 = undefined;
        temp_crypto.protectPacket(ct_payload, &tag, pt_payload.written(), header.written(), self.pktnum);

        // Generate the header protection sample.
        var sample_offset = try self.find_sample_offset();
        sample_offset -= header.written().len;
        const sample_len: usize = 16;
        var sample: [sample_len]u8 = undefined;
        @memcpy(&sample, ct_payload[sample_offset .. sample_offset + sample_len]);

        // Finally, apply header protection.
        const pn_offset = try self.find_pn_offset();
        try temp_crypto.protectHeader(header.written(), sample, pn_offset);

        // Append the header, protected payload, and tag.
        try w.writeAll(header.written());
        try w.writeAll(ct_payload);
        try w.writeAll(&tag);

        self.alloc.free(ct_payload);
    }

    // Read this packet from a buffer, e.g. received from a UDP socket.
    // TODO

    // Decode a packet header; return number of bytes read.
    // TODO: Only long headers supported.
    pub fn decode_header(self: *Self, buf: []const u8) !usize {
        var bytes_read: usize = 0;
        // TODO: Validate minimal length input.
        self.use_long_form = buf[0] & 0x80 == 0x80;
        self.version_specific_bits = buf[0] & 0x7F;
        self.version = std.mem.readInt(u32, buf[1..5], .big);
        self.dconn_id_len = buf[5];
        self.dconn_id = ConnectionId.init(buf[6 .. 6 + self.dconn_id_len], 0);
        bytes_read += 6 + self.dconn_id_len;
        self.sconn_id_len = buf[bytes_read];
        bytes_read += 1;
        self.sconn_id = ConnectionId.init(buf[bytes_read .. bytes_read + self.sconn_id_len], 0);
        bytes_read += self.sconn_id_len;

        // For QUICv1, check the fixed bit.
        if (self.version == QuicVersion1 and
            (self.version_specific_bits & 0x40 != 0x40))
        {
            return error.FixedBitError;
        }
        // See if anything further about the packet type can be determined.
        // - Check if Version 1, and Long, then look for type.
        if (self.version == QuicVersion1 and self.use_long_form) {
            const long_pkt_type = (self.version_specific_bits & 0x30) >> 4;
            if (long_pkt_type == @intFromEnum(QuicPktType.Initial)) {
                self.quic_pkt_type = QuicPktType.Initial;
                // Read token length and token.
                var token_len: u64 = undefined;
                token_len = try varint.readVarInt(buf[bytes_read..]);
                bytes_read += varint.decodedLen(buf[bytes_read]);
                self.token = try self.alloc.dupe(u8, buf[bytes_read .. bytes_read + token_len]);
                bytes_read += token_len;
                // Read overall length.
                self.len = try varint.readVarInt(buf[bytes_read..]);
                bytes_read += varint.decodedLen(buf[bytes_read]);
                // Read packet number.
                self.pktnum = buf[bytes_read];
                for (1..self.get_pktnum_len()) |i| {
                    self.pktnum <<= 8;
                    self.pktnum |= buf[bytes_read + i];
                }
            } else {
                return error.PacketTypeError;
            }
        }

        return bytes_read;
    }
};

const test_data = @import("test_data.zig");
test "header decode" {
    var p = QuicPacket.init(std.testing.allocator);
    _ = try p.decode_header(&test_data.client_header);
    try expectEqual(p.use_long_form, true);
    try expectEqual(p.version, QuicVersion1);
    try expectEqual(p.dconn_id_len, 8);
    try expectEqualSlices(u8, p.dconn_id.bytes, &[_]u8{ 0x83, 0x94, 0xc8, 0xf0, 0x3e, 0x51, 0x57, 0x08 });
    try expectEqual(p.sconn_id_len, 0);
    try expectEqual(p.quic_pkt_type, QuicPktType.Initial);
}

test "header pn and sample offset" {
    var p = QuicPacket.init(std.testing.allocator);
    defer p.deinit();
    _ = try p.decode_header(&test_data.client_header);

    try expectEqual(p.find_pn_offset(), 17);
    try expectEqual(p.find_sample_offset(), 21);
}

test "RFC 9001 client initial" {
    try test_data.loadTestData();
    var p = QuicPacket.init(std.testing.allocator);
    defer p.deinit();
    // Load the header and payload from RFC 9001.
    _ = try p.decode_header(&test_data.client_header);
    var f = frame.QuicFrame.init();
    defer f.deinit();
    try expectEqual(try f.decode(&test_data.client_body), test_data.client_body.len);
    try p.add_crypto_frame(f.body.CRYPTO.data);
    try p.add_padding(1162 - try p.get_payload_length());
    try expectEqual(p.get_payload_length(), 1162);

    // Check that the unprotected header matches.
    var hdr = std.Io.Writer.Allocating.init(std.testing.allocator);
    defer hdr.deinit();
    try p.serialize_header(&hdr.writer);
    try expectEqualSlices(u8, hdr.written(), &test_data.client_header);

    try expectEqual(p.find_pn_offset(), 18);
    try expectEqual(p.find_sample_offset(), 22);

    // Serialize protected packet to a buffer and check.
    var pkt_writer = std.Io.Writer.Allocating.init(std.testing.allocator);
    defer pkt_writer.deinit();
    try p.serialize(&pkt_writer.writer);
    try expectEqualSlices(u8, pkt_writer.written(), &test_data.client_packet);
}

test "make initial" {
    const rand = [_]u8{0} ** 32;
    var p = QuicPacket.init(std.testing.allocator);
    defer p.deinit();
    try p.make_initial(rand);

    try expectEqual(p.find_pn_offset(), 17);
    try expectEqual(p.find_sample_offset(), 21);
}

// TODO: support ability to aggregate multiple QUIC packets into a datagram,
// and to parse datagrams that contain multiple packets, per 8999.
